### ISSUE TITLE
Publish instance error

### ISSUE THREAD

**Issue by gborgono** [PerficientDigital/AEM-DataLayer#2]
Hi 
I get the following errors when open a page on the Publish Instance with Datalayer cloud service active, using anonymous user. 
javax.el.ELException: Error reading 'config' on type com.perficient.aem.datalayer.core.models.AEMDataLayerManager
If I use an authenticate user in the Administrator Group, it works and window.digitalData fields are populated. 

What authorization have I to set on publish instance to enable it ? 
Thanks a lot for any support
Giuseppe Borgonovo

**Comment by ghost** [comment]
Problem is the anonymous user is not able to read config from **_/etc/cloudservices/aemdatalayer_** on publish instance.
To avoid the problem, it is possible to set a **rep:policy** node under _/etc/cloudservices/aemdatalayer_ configuration to grant access to "everyone" user/group or better to define a proper user (to replicate it on publish istance) to be able to read config settings from /etc/cloudservices/aemdatalayer.
For instance, you can use the ootb user dtmservice and set **ALLOW** **_jcr:read_** under _/etc/cloudservices/aemdatalayer_ path.

Thanks
Gaetano Polizzi

**Comment by gborgono** [comment]
Thanks Gaetano; it works with this setting. 
Ciao
Giuseppe

**Comment by polizzigaetano** [comment]
you are welcome Giuseppe!

Ciao
Gaetano
