### ISSUE TITLE
Using OTB JSON Exporter opposed to Gson

### ISSUE THREAD

**Issue by bsaravanaprakash** [PerficientDigital/AEM-DataLayer#8]
Can we refactor / provide an example to reuse otb jackson json exporter rather than using gson? This becomes otb and easy when I extend otb components and want the @jsonignore properties to get excluded automatically without additional massage.

**Comment by klcodanr** [comment]
@bsaravanaprakash  I'd be happy to merge a PR for this functionality.

**Comment by klcodanr** [comment]
Fixed in eec02d7c8703c863b266f86e65e8a101f5529d53
